version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mariadb:11.2.3
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            PMA_HOST: db
        ports:
            - "8080:80"
        depends_on:
            - db
